# Generated by Django 4.2.5 on 2023-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_usermangahistory_last_view_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermangahistory',
            name='follow_updates',
            field=models.BooleanField(default=False),
        ),
    ]
