# Generated by Django 4.2.5 on 2023-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_usermangahistory_last_view_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangahistory',
            name='last_view_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
