# Generated by Django 4.2.5 on 2023-09-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='name',
            new_name='title',
        ),
    ]
