# Generated by Django 4.2.5 on 2023-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_rename_name_manga_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
