# Generated by Django 4.2.5 on 2023-09-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_remove_manga_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='created',
        ),
    ]
