# Generated by Django 4.2.5 on 2023-09-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_remove_manga_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
