# Generated by Django 4.2.5 on 2023-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_chapter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='preview_img',
            field=models.URLField(blank=True),
        ),
    ]
