# Generated by Django 4.2.5 on 2023-09-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_manga_preview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='images',
            field=models.JSONField(null=True),
        ),
    ]
