# Generated by Django 4.2.5 on 2023-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_alter_chapter_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
