# Generated by Django 4.2.5 on 2023-10-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='first_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_manga', to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='manga',
            name='last_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_manga', to='manga.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
