# Generated by Django 4.2.5 on 2023-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_remove_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
